apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-quack-server.fullname" . }}
  labels:
    {{- include "simple-quack-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: quack
      protocol: TCP
      name: quack
  selector:
    {{- include "simple-quack-server.selectorLabels" . | nindent 4 }}
